site_name: "EpikSploit FrameWork Pentesting"
repo_url: https://github.com/MirageSh/EpikSploit
site_author: epiksploit.com
docs_dir: docs
nav:
  - Introduction: index.md
  - 'Quick Start': quickstart.md
  - 'New Modules': newmodules.md
  - Scenarios: scenario.md
  - Scenarios:
    - 'Hobbico C-me - Changing SSID': scenarios/hobbico-cme.md
    - 'Hobbico Flitt - Power Off': scenarios/hobbico-flitt.md
    - 'DJI Tello - Landing': scenarios/dji-tello.md
extra:
  mailto: contact@epiksploit.com
theme:
  name: readthedocs
  locale: en
  highlightjs: true
  navigation_depth: 8
  collapse_navigation: true
  hljs_languages:
    - yaml
    - python
    - console
extra_javascript:
  - js/collapsible-navbar.js
  - js/theme.js
use_directory_urls: false
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.details
  - toc:
      permalink: True